import streamlit as st
import pickle
import requests
from requests.auth import HTTPBasicAuth

# -----------------------------
# LOAD ML MODEL
# -----------------------------

svm_model = pickle.load(open("svm_model.pkl", "rb"))
vectorizer = pickle.load(open("vectorizer.pkl", "rb"))

# -----------------------------
# JIRA CONFIG
# -----------------------------

EMAIL = "YOUR_MAIL"
API_TOKEN = "YOUR_API_TOKEN"
BASE_URL = "https://compliance-sentinel-demo1.atlassian.net"

PROJECT_KEY = "KAN"   # change if your Jira project key is different

auth = HTTPBasicAuth(EMAIL, API_TOKEN)

headers = {
    "Accept": "application/json",
    "Content-Type": "application/json"
}

# -----------------------------
# CREATE JIRA ISSUE
# -----------------------------

def create_jira_issue(title, description):

    url = f"{BASE_URL}/rest/api/3/issue"

    payload = {
        "fields": {
            "project": {
                "key": PROJECT_KEY
            },
            "summary": title,
            "description": {
                "type": "doc",
                "version": 1,
                "content": [{
                    "type": "paragraph",
                    "content": [{
                        "type": "text",
                        "text": description
                    }]
                }]
            },
            "issuetype": {
                "name": "Task"
            }
        }
    }

    response = requests.post(
        url,
        headers=headers,
        auth=auth,
        json=payload
    )

    if response.status_code == 201:
        return response.json()["key"]
    else:
        return None


# -----------------------------
# UPDATE JIRA WITH RESULT
# -----------------------------

def update_jira_with_result(issue_key, prediction, score, action):

    comment = f"""
AI Compliance Analysis Result

Risk Prediction: {prediction}

Explanation Score: {round(score,3)}

Compliance Action: {action}

Generated by AI Compliance Sentinel
"""

    url = f"{BASE_URL}/rest/api/3/issue/{issue_key}/comment"

    payload = {
        "body": {
            "type": "doc",
            "version": 1,
            "content": [{
                "type": "paragraph",
                "content": [{
                    "type": "text",
                    "text": comment
                }]
            }]
        }
    }

    requests.post(
        url,
        headers=headers,
        auth=auth,
        json=payload
    )


# -----------------------------
# STREAMLIT PAGE CONFIG
# -----------------------------

st.set_page_config(
    page_title="AI Compliance Sentinel",
    page_icon="🛡",
    layout="wide"
)

# -----------------------------
# CUSTOM STYLE
# -----------------------------

st.markdown("""
<style>

.main-title {
    font-size:42px;
    font-weight:bold;
    text-align:center;
    padding:20px;
    border-radius:10px;
    background: linear-gradient(90deg,#4b6cb7,#182848);
    color:white;
}

.clean-box {
    padding:20px;
    border-radius:10px;
    background:linear-gradient(135deg,#a8ff78,#78ffd6);
    text-align:center;
    font-size:22px;
}

.risk-box {
    padding:20px;
    border-radius:10px;
    background:linear-gradient(135deg,#ff6a6a,#ff0000);
    text-align:center;
    font-size:22px;
    color:white;
}

.metric-box {
    padding:15px;
    border-radius:10px;
    background:#f4f4f4;
    text-align:center;
}

</style>
""", unsafe_allow_html=True)

# -----------------------------
# HEADER
# -----------------------------

st.markdown('<div class="main-title">🛡 AI Compliance Sentinel</div>', unsafe_allow_html=True)

st.write("Analyze AI project proposals and automatically generate compliance reports.")

st.divider()

# -----------------------------
# EXAMPLE LOADER
# -----------------------------

example_text = """
The Human Resources department proposes an AI system that automatically ranks job applicants based on historical hiring data and behavioral indicators extracted from video interviews.
"""

if st.button("Load Example Proposal", key="load_example"):
    st.session_state["proposal"] = example_text

# -----------------------------
# USER INPUT
# -----------------------------

title = st.text_input("Proposal Title")

proposal = st.text_area(
    "Proposal Description",
    value=st.session_state.get("proposal",""),
    height=200
)

st.divider()

# -----------------------------
# ANALYSIS BUTTON
# -----------------------------

if st.button("Analyze Proposal", key="analyze"):

    if proposal.strip() == "":
        st.warning("Please enter a proposal description")

    else:

        vec = vectorizer.transform([proposal])

        prediction = svm_model.predict(vec)[0]

        score = svm_model.decision_function(vec)[0]

        action = "Review Required" if prediction == "red_flag" else "Approved"

        st.subheader("Compliance Analysis")

        col1, col2, col3 = st.columns(3)

        with col1:
            st.markdown(
                f'<div class="metric-box"><b>Prediction</b><br>{prediction.upper()}</div>',
                unsafe_allow_html=True
            )

        with col2:
            st.markdown(
                f'<div class="metric-box"><b>Explanation Score</b><br>{round(score,3)}</div>',
                unsafe_allow_html=True
            )

        with col3:
            st.markdown(
                f'<div class="metric-box"><b>Compliance Action</b><br>{action}</div>',
                unsafe_allow_html=True
            )

        st.divider()

        # -----------------------------
        # RISK DISPLAY
        # -----------------------------

        if prediction == "red_flag":
            st.markdown('<div class="risk-box">⚠ High Risk Detected</div>', unsafe_allow_html=True)
        else:
            st.markdown('<div class="clean-box">✅ Proposal Appears Compliant</div>', unsafe_allow_html=True)

        

        # -----------------------------
        # CREATE JIRA ISSUE
        # -----------------------------

        issue_key = create_jira_issue(title, proposal)

        if issue_key:

            st.success(f"Jira Issue Created: {issue_key}")

            update_jira_with_result(issue_key, prediction, score, action)

            st.success("Compliance result stored in Jira")


        else:

            st.error("Failed to create Jira issue")

st.divider()

st.caption("AI Compliance Sentinel – AI Governance Prototype")